### PR TITLE
Better download handling and fix typo in readme

### PR DESCRIPTION
**Pull request by stepri**

### CODE REVIEW

**Comment by stofstik** [comment]
w00t! Does this fix the Buffer toString() error?

**Comment by brendannee** [comment]
How common is the "realtime_trip_id" field in trips.txt in GTFS files? Is this something a lot of agencies are likely to have, or is it a one-off thing for a specific agency?

**Comment by stepri** [comment]
@stofstik For me it worked with this improved code.
@brendannee I'm not really a GTFS expert, but I needed this to be an index for speed improvements.

**Comment by brendannee** [comment]
This looks good - I accepted it but then made a few changes to use the "node-fetch" module instead of "request" and to use promises instead.

I also removed the "realtime_trip_id" field from trip.txt since I haven't seen anything about this field being commonly used. @stepri Does the GTFS file you are using contain this field?

Try out the latest code on the "master" branch and let me know if you have any problems and if the "Buffer toString()" issue is solved.

**Pull request merged**
