### PR TITLE
Faster import of GTFS to DB

### PR DESCRIPTION
**Pull request by laem**
I've identified that importing lines is a big bottleneck. I see a few reasons for this : 
- formatting each line takes time
- reading the CSV in JS and creating the 8000 lines batch can take time too
- inserting to the DB by batched of 8000

See this PR as trial and errors to divide by 10 the import times :)

### CODE REVIEW

**Comment by brendannee** [comment]
Thanks for pointing this out and testing everything. 

I'll work on getting this implemented.

**Comment by laem** [comment]
I was trying to use the native CLI sqlite3 ".import" feature, that can import CSV. From my first test, writing to CSV in JS and then importing through exec() looks way faster. 

One other technique would be to wrap the prepare.run() calls in a transaction(). From what people are saying, this would speed the process by a lot. 

Not sure I'll have time in the next days to finish this PR.

**Comment by laem** [comment]
Looks like my db creation misses two things :
- indexes
- void tables from what I can see

**Comment by laem** [comment]
OK, now that I use the createTables function, ints are treated as strings by .import

**Pull request closed without merging**
