### PR TITLE
Migrate to typescript

### PR DESCRIPTION
**Pull request by anbraten**
I had a look if it would make sense to migrate this library to typescript. 
Would be interested if this is a thing you would consider. 
If so I would be happy to finish this migration.

### CODE REVIEW

**Comment by brendannee** [comment]
This would be great! I'd love to have it migrated to typescript.

If you want to finish this migration and let me know, I can review and help in any way.

**Comment by brendannee** [comment]
Let me know if you need any help or have questions as part of this migration - I'm very interested to migrate to Typescript and appreciate your efforts so far.

**Comment by anbraten** [comment]
I did some improvements based on this repo in my own project for now: https://github.com/kiel-live/transport-hub/tree/main/importer

Next I would try to bring those improvements back here. Somehow I also finally solved the out-of-memory issue I had before, but I still have no idea what was the issue before.

**Comment by brendannee** [comment]
I just pushed an updated version https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.13.0 which converts this library to Typescript and updates several other things.  Check it out and let me know if you have suggestions on how to improve it or see any issues.

**Pull request closed without merging**
